package net.euler.problem002;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
 * 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */
public class Problem {
	public static void main(String[] args) {
		System.out.println(getSumOfEvenFibonacci(4000000));
	}

	static int getSumOfEvenFibonacci(int max) {
		int curr = 2, prev = 1;
		int temp;
		int sum = 0;

		while (curr < max) {
			if (curr % 2 == 0)
				sum += curr;

			temp = curr;
			curr = curr + prev;
			prev = temp;
		}

		return sum;
	}
}
